- interface/elements/msc-profile-view/msc-profile-view.html
> Change Coinbase to Primary

- config/config.std.js
- hub/web3-connector.js
- interface/bower.json
- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
- some layout change (moving account tool buttons above, etc.)
- the local enode sometimes fetched incorrectly, need more testing
- the shared public enodes list removed from main UI, hopefully can be added into dialog
> several changes to make outlooking more balanced, and minor fixes

- README.md
- linux-setup.sh
nothing special but some clearer instructions.
> update exe name to readme and put more instructions under linux

- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
Might be considered as hacky way, but its a lot easier to implement, and it doesn't even needs user to be fully synced.
> Quick access to explorer

- BOUNTY.md
- README.md
@immartian Please review and merge.
> Add bty program guidelines

- README.md
- hub/locale.js
- interface/elements/elements.html
- interface/elements/msc-element/msc-element.html
- interface/elements/msc-profile-view/msc-profile-view.css
- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
- interface/elements/msc-subcomponents/msc-main-status/msc-main-status.css
- interface/elements/msc-subcomponents/msc-main-status/msc-main-status.html
- interface/elements/msc-subcomponents/msc-main-status/msc-main-status.js
This commit is for issue #67.
* Rearranged the chain-status elements (called main-status now).
* Shrinked the table headers and the wallets font size.
* Moved the main status component from msc-element to profile-view
* Added a missing dot in the README regarding nw.
* Minor syntax fixes here and there.
Enjoy, my best whishes to MUSIC ppl.
> UI enhancements

- interface/elements/msc-simple-login-view/msc-simple-login-view.js
- interface/elements/msc-subcomponents/msc-main-status/msc-main-status.js
And fixed a NaN issue in the block ti
> Check timesync every 2 mins

- interface/bower.json
- interface/elements/msc-profile-view/msc-profile-view.css
- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
- interface/styles/shared-styles.html
Ability to select account on send action
> Dropdown for send funds action

- interface/elements/msc-profile-view/msc-profile-view.css
- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
- interface/images/icons/arrow.svg
* Send confirmation dialog
*  Style account details and send dialogs with avatars
> Send confirmation dialog and etc

- interface/elements/msc-introduction/msc-introduction.css
- interface/elements/msc-introduction/msc-introduction.html
- interface/elements/msc-introduction/msc-introduction.js
- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
-  Fix dialogs focus (make sure important data always cleared)
- Update intoduction
- etc
>  Fix dialogs focus (make sure important data always cleared), update introduction and etc

- interface/elements/msc-introduction/msc-introduction.js
- interface/elements/msc-profile-view/msc-profile-view.js
Fix incorrect join order under Windows, error in intro and decrease logging.
> Fix incorrect join order under Windows

- facade/client-utils.js
- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
- package.json
- Rewrite coinmarketcap api
- Remove unused dependency
> Rewrite coinmarketcap api; remove unused dependency

- README.md
Add links, fix slightly incorrect information and change order to show x64 releases first
> Add links and fix slightly incorrect information

- interface/bower.json
Resolve bower install automatically
> Resolve bower install

- interface/elements/msc-introduction/msc-introduction.html
- interface/elements/msc-introduction/msc-introduction.js
Show account address after import in the introduction
> Show account address after import in intro

- hub/msc.js
Fix in home/APPDATA config was never used
> Fix in home/APPDATA config was never used

- interface/elements/msc-introduction/msc-introduction.js
- interface/elements/msc-profile-view/msc-profile-view.js
Might as well speed up mnemonic account creation (file copy) on slow machines.
> Copy important files in the sync mode

- package.json
give a version for nw specifically - fixes build failures attempting to include ffmpeg
> fix for ffmpeg integration

- .snyk
- interface/elements/msc-profile-view/msc-profile-view.css
- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
- interface/elements/msc-subcomponents/msc-main-status/msc-main-status.css
- interface/elements/msc-subcomponents/msc-main-status/msc-main-status.html
- interface/styles/locales/ru.json
- package.json
- yarn.lock
- Tabs
- Clipboard
- Cookies
- Only show txid, after transaction was made
- Various style fixes
- Make wallet `yarn` package,json minimal and compatible with Windows (back to XP) and Linux again
- Readd snyk patching back
- Anything I might forget about
> Varios Walllet Fixes

- interface/elements/msc-profile-view/msc-profile-view.html
- interface/elements/msc-profile-view/msc-profile-view.js
> Reduce navbar ; correct bug
